export const UPDATE_TECH_COURSES='UPDATE_TECH_COURSES';
export const UPDATE_NON_TECH_COURSES='UPDATE_NON_TECH_COURSES';
export const UPDATE_SKILL_BASED_COURSES='UPDATE_SKILL_BASED_COURSES';
export const UPDATE_ACTIVE_COURSE='UPDATE_ACTIVE_COURSE';
